### ISSUE TITLE
Crash on other users when one user exit the server

### ISSUE THREAD

**Issue by nhtvinh** [DNAlchemist/minecraft-skinny#4]
Hi, 

I faced this issue when setting up a local server and play the game with my friends, we can use our own skin, but when one friend exit the game, the others will crash the game with the following issue:
-------------------------------------------------------------------------------------
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 9/3/18 10:39 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at one.chest.minecraft.ssskins.TextureLocator.loadTexture(TextureLocator.java:54)
	at one.chest.minecraft.ssskins.client.ClientSideEventObserver.onPlayerRenderEvent(ClientSideEventObserver.java:32)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_ClientSideEventObserver_onPlayerRenderEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at info.mineshafter.GameStarter.main(GameStarter.java:33)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at one.chest.minecraft.ssskins.TextureLocator.loadTexture(TextureLocator.java:54)
	at one.chest.minecraft.ssskins.client.ClientSideEventObserver.onPlayerRenderEvent(ClientSideEventObserver.java:32)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_ClientSideEventObserver_onPlayerRenderEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityOtherPlayerMP)
	Entity ID: 422
	Entity Name: meow_meow
	Entity's Exact location: 74.40, 72.56, 177.58
	Entity's Block location: World: (74,72,177), Chunk: (at 10,4,1 in 4,11; contains blocks 64,0,176 to 79,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@272a5bc6
	Location: 0.85,0.00,-0.64 - World: (0,0,-1), Chunk: (at 0,0,15 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 28.125
	Delta: 0.93998957
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DarkNinjaSuraki'/167, l='MpServer', x=73.55, y=72.56, z=178.22]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-6,65,135), Chunk: (at 10,4,7 in -1,8; contains blocks -16,0,128 to -1,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 640645 game time, 680650 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntityPlayerSP['DarkNinjaSuraki'/167, l='MpServer', x=73.55, y=72.56, z=178.22], EntityChicken['Chicken'/130, l='MpServer', x=103.20, y=73.00, z=109.56], EntityBat['Bat'/515, l='MpServer', x=150.76, y=43.86, z=175.22], EntityChicken['Chicken'/132, l='MpServer', x=99.78, y=80.00, z=127.92], EntityChicken['Chicken'/134, l='MpServer', x=118.19, y=72.00, z=102.49], EntitySpider['Spider'/137, l='MpServer', x=113.70, y=27.10, z=167.00], EntityZombie['Zombie'/650, l='MpServer', x=123.50, y=15.00, z=120.50], EntityZombie['Zombie'/139, l='MpServer', x=123.50, y=36.00, z=162.50], EntitySkeleton['Skeleton'/399, l='MpServer', x=5.50, y=11.00, z=235.50], EntityBat['Bat'/534, l='MpServer', x=22.74, y=18.00, z=100.49], EntityBat['Bat'/409, l='MpServer', x=146.99, y=40.43, z=147.62], EntityBat['Bat'/410, l='MpServer', x=147.36, y=40.16, z=156.47], EntityCreeper['Creeper'/922, l='MpServer', x=137.50, y=41.00, z=226.50], EntityBat['Bat'/288, l='MpServer', x=1.56, y=11.20, z=202.54], EntitySkeleton['Skeleton'/806, l='MpServer', x=24.50, y=37.00, z=108.10], EntityZombie['Zombie'/40, l='MpServer', x=-2.50, y=14.00, z=212.50], EntityZombie['Zombie'/552, l='MpServer', x=1.50, y=54.00, z=99.50], EntityZombie['Zombie'/41, l='MpServer', x=-2.50, y=15.00, z=215.28], EntitySkeleton['Skeleton'/553, l='MpServer', x=39.50, y=34.00, z=186.50], EntitySkeleton['Skeleton'/554, l='MpServer', x=38.50, y=34.00, z=186.50], EntitySkeleton['Skeleton'/555, l='MpServer', x=42.50, y=34.00, z=187.50], EntityZombie['Zombie'/811, l='MpServer', x=53.77, y=30.00, z=98.51], EntityZombie['Zombie'/556, l='MpServer', x=41.50, y=34.00, z=187.50], EntitySkeleton['Skeleton'/812, l='MpServer', x=57.50, y=29.00, z=99.50], EntitySkeleton['Skeleton'/174, l='MpServer', x=137.73, y=35.00, z=162.47], EntitySkeleton['Skeleton'/942, l='MpServer', x=-2.50, y=21.00, z=109.50], EntityBat['Bat'/175, l='MpServer', x=141.75, y=41.10, z=173.50], EntitySpider['Spider'/49, l='MpServer', x=6.50, y=19.00, z=146.50], EntityBat['Bat'/178, l='MpServer', x=131.50, y=20.46, z=180.52], EntityZombie['Zombie'/50, l='MpServer', x=5.50, y=19.00, z=149.50], EntityZombie['Zombie'/308, l='MpServer', x=28.51, y=31.00, z=125.22], EntitySpider['Spider'/53, l='MpServer', x=13.04, y=45.00, z=253.88], EntityZombie['Zombie'/309, l='MpServer', x=26.50, y=31.00, z=122.50], EntitySkeleton['Skeleton'/567, l='MpServer', x=54.50, y=44.00, z=215.50], EntityCreeper['Creeper'/823, l='MpServer', x=49.50, y=26.00, z=223.50], EntitySquid['Squid'/312, l='MpServer', x=19.26, y=63.16, z=195.14], EntitySkeleton['Skeleton'/568, l='MpServer', x=54.50, y=44.00, z=217.50], EntityCreeper['Creeper'/824, l='MpServer', x=48.50, y=26.00, z=222.50], EntitySquid['Squid'/313, l='MpServer', x=15.84, y=63.51, z=191.41], EntityCreeper['Creeper'/825, l='MpServer', x=49.50, y=26.00, z=224.50], EntitySquid['Squid'/314, l='MpServer', x=18.69, y=61.00, z=194.89], EntitySquid['Squid'/315, l='MpServer', x=20.60, y=61.31, z=192.47], EntityCreeper['Creeper'/571, l='MpServer', x=104.50, y=6.00, z=218.50], EntityWitch['Witch'/61, l='MpServer', x=18.53, y=44.00, z=111.73], EntityWitch['Witch'/62, l='MpServer', x=19.01, y=44.00, z=114.56], EntitySkeleton['Skeleton'/194, l='MpServer', x=135.50, y=36.00, z=125.30], EntityChicken['Chicken'/195, l='MpServer', x=134.40, y=78.00, z=124.15], EntityItem['item.item.egg'/196, l='MpServer', x=134.15, y=78.00, z=124.63], EntityCreeper['Creeper'/70, l='MpServer', x=47.50, y=36.00, z=99.50], EntityCreeper['Creeper'/199, l='MpServer', x=152.77, y=35.00, z=119.47], EntityBat['Bat'/72, l='MpServer', x=35.52, y=32.52, z=132.17], EntityBat['Bat'/73, l='MpServer', x=44.19, y=35.06, z=188.66], EntitySkeleton['Skeleton'/201, l='MpServer', x=136.28, y=36.00, z=121.53], EntityCreeper['Creeper'/713, l='MpServer', x=3.50, y=29.00, z=251.50], EntityCreeper['Creeper'/715, l='MpServer', x=43.81, y=28.00, z=204.47], EntityChicken['Chicken'/205, l='MpServer', x=143.89, y=76.00, z=237.11], EntityZombie['Zombie'/333, l='MpServer', x=27.50, y=30.00, z=148.50], EntitySkeleton['Skeleton'/83, l='MpServer', x=55.50, y=29.00, z=223.50], EntityCreeper['Creeper'/84, l='MpServer', x=54.50, y=29.00, z=220.17], EntityZombie['Zombie'/85, l='MpServer', x=51.50, y=46.00, z=233.50], EntityBat['Bat'/214, l='MpServer', x=150.24, y=39.54, z=149.44], EntitySkeleton['Skeleton'/726, l='MpServer', x=20.50, y=37.00, z=112.50], EntityBat['Bat'/87, l='MpServer', x=78.25, y=51.10, z=162.16], EntityZombie['Zombie'/727, l='MpServer', x=20.50, y=37.00, z=115.50], EntityBat['Bat'/88, l='MpServer', x=76.30, y=51.10, z=163.67], EntityBat['Bat'/89, l='MpServer', x=75.25, y=49.00, z=160.52], EntityBat['Bat'/90, l='MpServer', x=78.75, y=49.00, z=161.25], EntityItemFrame['entity.ItemFrame.name'/91, l='MpServer', x=68.03, y=74.50, z=183.50], EntityItemFrame['entity.ItemFrame.name'/92, l='MpServer', x=68.03, y=74.50, z=182.50], EntityItemFrame['entity.ItemFrame.name'/93, l='MpServer', x=68.03, y=74.50, z=181.50], EntitySpider['Spider'/349, l='MpServer', x=18.51, y=47.00, z=102.03], EntityItemFrame['entity.ItemFrame.name'/94, l='MpServer', x=68.03, y=74.50, z=179.50], EntityItemFrame['entity.ItemFrame.name'/95, l='MpServer', x=68.03, y=74.50, z=178.50], EntityCreeper['Creeper'/479, l='MpServer', x=40.50, y=21.00, z=101.50], EntityItemFrame['entity.ItemFrame.name'/96, l='MpServer', x=68.03, y=74.50, z=184.50], EntityEnderman['Enderman'/97, l='MpServer', x=82.41, y=70.00, z=191.49], EntityCreeper['Creeper'/481, l='MpServer', x=25.50, y=12.00, z=142.50], EntityCreeper['Creeper'/615, l='MpServer', x=28.50, y=21.00, z=99.50], EntityChicken['Chicken'/112, l='MpServer', x=101.41, y=74.00, z=114.88], EntityCow['Cow'/113, l='MpServer', x=92.53, y=77.00, z=119.20], EntitySpider['Spider'/114, l='MpServer', x=94.97, y=72.00, z=155.89], EntityCreeper['Creeper'/115, l='MpServer', x=92.13, y=69.00, z=164.74], EntityBat['Bat'/755, l='MpServer', x=38.25, y=36.00, z=128.51], EntityChicken['Chicken'/116, l='MpServer', x=89.80, y=69.00, z=223.46], EntityItem['item.item.egg'/117, l='MpServer', x=89.25, y=68.00, z=224.25], EntityCreeper['Creeper'/508, l='MpServer', x=41.50, y=56.00, z=146.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at info.mineshafter.GameStarter.main(GameStarter.java:33)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-134-generic
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 313716312 bytes (299 MB) / 657301504 bytes (626 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2756 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID           | Version      | Source                          | Signature                                |
	|:------ |:------------ |:------------ |:------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft    | 1.12.2       | minecraft.jar                   | None                                     |
	| UCHIJA | mcp          | 9.42         | minecraft.jar                   | None                                     |
	| UCHIJA | FML          | 8.0.99.99    | forge-1.12.2-14.23.4.2756.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge        | 14.23.4.2756 | forge-1.12.2-14.23.4.2756.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | atimemod2    | 2.0.9        | atimemod2-2.0.9.jar             | None                                     |
	| UCHIJA | llibrary     | 1.7.15       | llibrary-1.7.15-1.12.2.jar      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJA | dragonmounts | 1.12.2-1.4.4 | DragonMounts-1.12.2-1.4.4.jar   | None                                     |
	| UCHIJA | ssskins      | 0.0.1        | ssskins-0.0.1.jar               | None                                     |
	| UCHIJA | jurassicraft | 2.1.10       | JurassiCraft2-1.12.2-2.1.10.jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 18.0.5' Renderer: 'Mesa DRI Intel(R) Haswell Mobile '
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2756
	LWJGL: 2.9.4
	OpenGL: Mesa DRI Intel(R) Haswell Mobile  GL version 3.0 Mesa 18.0.5, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz

**Comment by DNAlchemist** [comment]
Duplicate #3
